# action.yml
name: CI

description: 'CI Action'

inputs:
  src_path:
    description: Path of source (relative path from /github/workspace)
    required: true
  bluez_path:
    description: Path of bluez source (relative path from /github/workspace)
    required: true
  output_path:
    description: Output path (relative path from /github/workspace)
    required: false
    default: results
  github_token:
    description: github_token
    required: true
  email_token:
    description: Email token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src_path }}
    - ${{ inputs.bluez_path }}
    - ${{ inputs.output_path }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
